### ISSUE TITLE
PiCrust2 categorize_by_function.py 

### ISSUE THREAD

**Issue by zeinabourhane** [gavinmdouglas/picrust2_manuscript#1]
Hello,
I'm just wondering if there is a categorize_by_function.py script within PiCrust2 in order to collapse the pathways into higher level of the pathway hierarchy?
I've successfully produced the KO_metagenome_out, EC_metagenome_out, but I'm still only able to run and visualize on individual KO instead of functional groups.
Any thoughts?
 Thank you

**Comment by gavinmdouglas** [comment]
Hey @zina-R,

I wrote a response to this question, which you can see here: https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#how-can-i-run-categorize_by_functionpy-like-in-picrust1

Please let me know if you need further clarification.

All the best,

Gavin

**Comment by zeinabourhane** [comment]
Hello  @gavinmdouglas , 
Thank you for your answer, well i am confused ! I am not understanding how can i switch from picrust2 tutorial ( results: description of each KO and EC ...)  which we used fasta and biom files to this function " categorize_by_function.py"  . If i well understand i need to repeat all the steps (Normalize OTU Table, Predict Functions For Metagenome, Collapse predictions into pathways ) ? 
Best ,

**Comment by gavinmdouglas** [comment]
Hi @zina-R,

If you're comfortable in R you can use the R script linked to in that FAQ response. Otherwise yes you will need to run all of the PICRUSt1 scripts to get KEGG pathways in the format of "categorize_by_function.py".


Cheers,

Gavin

**Comment by zeinabourhane** [comment]
Hello @gavinmdouglas ,
I would like to ask you, if the biom file used in picrust2 is the same of picrust1. for example in this command :
****normalize_by_copy_number.py**
      --gg_version 18may2012
      -i hmp_mock_16S.biom
      -o normalized_otus.biom
can i use the same biom that i used in picrust2, note that i didn t use quiime to execute otu table. 
Best,

**Comment by zeinabourhane** [comment]
Hello again @gavinmdouglas 
I am trying to do it in R  as mentionned in the script, i had an error : object 'kegg_brite_map' not found
while running the function.
if i well understand i need to run picrust1 to get ''kegg_brite_map ??
if yes why we are doing other methods if we need to pass by picrust1 in all cases ?? i am so confused

##kegg_brite_map <- read.table("/path/to/picrust1_KO_BRITE_map.tsv", header=TRUE, sep="\t", quote = "", stringsAsFactors = FALSE, comment.char="", row.names=1) 
This file is picrust1 output ??
Best,

**Comment by gavinmdouglas** [comment]
Hey @zina-R ,

No you don't need to run PICRUSt1. See this part of the FAQ:

"You can download the R code here: https://www.dropbox.com/s/91pohevw4ayxtn2/picrust1_categorize_by_func.R?dl=1 and the legacy table of mappings from KOs to BRITE hierarchy here (which is a required input file): https://www.dropbox.com/s/a5o4li0irsqupt3/picrust1_KO_BRITE_map.tsv?dl=1."

You need to run in `picrust1_KO_BRITE_map.tsv` after downloading it (which you can do by uncommenting that line you posted).


Cheers,

Gavin

**Comment by zeinabourhane** [comment]
Hi @gavinmdouglas 
In this commande it is mention pred_metagenome_strat.tsv
## pathway_pipeline.py -i KO_metagenome_out/pred_metagenome_strat.tsv -o KEGG_pathways_out --no_regroup --map picrust2/picrust2/default_files/pathway_mapfiles/KEGG_pathways_to_KO.tsv

I am trying to follow the script to get the strat.tv output and use it tin the previous command but i get the unstrat.tsv.gz , i already added --strat_out as below, how can i get it  ?

place_seqs.py -s SWARM_OTUs_curated.fasta -o placed_seqs.tre -p 1 --intermediate placement_working

### 2-Hidden state prediction
hsp.py -i 16S -t placed_seqs.tre -o marker_nsti_predicted.tsv.gz -p 1 -n
hsp.py -i EC -t placed_seqs.tre -o EC_predicted.tsv.gz -p 1
hsp.py -i KO -t placed_seqs.tre -o KO_predicted.tsv.gz -p 1

### 3-Metagenome prediction
metagenome_pipeline.py -i SWARM_table_curated.biom \
                       -m marker_nsti_predicted.tsv.gz \
                       -f EC_predicted.tsv.gz \
                       -o EC_metagenome_out --strat_out
					   
metagenome_pipeline.py -i SWARM_table_curated.biom \
                       -m marker_nsti_predicted.tsv.gz \
                       -f KO_predicted.tsv.gz \
                       -o KO_metagenome_out --strat_out 

Best,

**Comment by mikelgutmut** [comment]
Good afternoon, 
I am writing in relation to some further issues with this process.
I've followed the steps involving the R function as indicated by @gavinmdouglas and I was successfully able to reproduce them. As a result, I got three separate datasets, each one belonging to a different KO level. However, I intend to use my dataset for further analysis via LEfSe for functional biomarker analysis and for this I would like to have the information of the 3 levels all in the same data table to later create a cladogram (with taxonomic data you can include different hierarchical taxonomical levels separated by | and this is what I am trying to do with the functional data).
Could anyone help me on solving this? Does anyone know if there is a way to get this final output?
Thanks in advance, Mikel.

**Comment by Saldiyan** [comment]
Hello, 

I am a new user to PICRUST software package. I am running the below command, the folder "KO_metagenome_out" is made but there is no output in the folder (The folder is empty), I tried to re-run the command but got same issue, please let me know if you have any opinion about solving this issue. Thank you. 

metagenome_pipeline.py -i feature-table.biom -m marker_predicted_and_nsti.tsv.gz -f KO_predicted.tsv.gz -o KO_metagenome_out --strat_out

**Comment by mikelgutmut** [comment]
Hey,

First of all, sorry for the late reply, I was out of "service" for a while.
Sadly I cannot help you since I worked with PICRUST as a part of an
internship but I'm not an expert at all.

Good luck with it,

Mikel.

**Comment by Bhagyashri199** [comment]
hi there,
I have ran the command for categorizing the picrust2 output to higher level using below command
pathway_pipeline.py -i KO_metagenome_out/pred_metagenome_strat.tsv -o KEGG_pathways_out --no_regroup --map picrust2/picrust2/default_files/pathway_mapfiles/KEGG_pathways_to_KO.tsv
and it was successful.
Now my question is how can I convert this KEGG_pathways_out file to KEGG pathway to run in the STAMP.

**Comment by mikelgutmut** [comment]
Hey,

First of all, sorry for the late reply, I was out of "service" for a while.
Sadly I cannot help you since I worked with PICRUST as a part of an
internship but I'm not an expert at all.

Good luck with it,

Mikel.

**Comment by EJS01** [comment]
Hi, I am trying to generate the hierarchy of functions, but the server is now unavailable. Can you reupload the required inputs and R Codes?

https://www.dropbox.com/scl/fi/xxr4vsj74ibc9i46vh0go/picrust1_KO_BRITE_map.tsv?rlkey=1g10sarlk0ew9pfbtgkd0jgwl&dl=1
https://www.dropbox.com/scl/fi/yhxjae5bvupspx0wf6c0b/picrust1_categorize_by_func.R?rlkey=g2li7l96l8tlsryiya5f5jx8a&dl=1

**Comment by gavinmdouglas** [comment]
Hi @EJS01 ,

Those links were broken for a while, sorry -- they're working again!


Cheers,

Gavin

**Comment by EJS01** [comment]
> Hey @zina-R ,
> 
> No you don't need to run PICRUSt1. See this part of the FAQ:
> 
> "You can download the R code here: https://www.dropbox.com/s/91pohevw4ayxtn2/picrust1_categorize_by_func.R?dl=1 and the legacy table of mappings from KOs to BRITE hierarchy here (which is a required input file): https://www.dropbox.com/s/a5o4li0irsqupt3/picrust1_KO_BRITE_map.tsv?dl=1."
> 
> You need to run in `picrust1_KO_BRITE_map.tsv` after downloading it (which you can do by uncommenting that line you posted).
> 
> Cheers,
> 
> Gavin

Hi Gavin,

May I know the year of this BRITE map? Can I have the latest one, if you have any?

**Comment by gavinmdouglas** [comment]
Hi @EJS01,

I don't have a version number for that map file, but I believe it corresponds to the last openly available version of KEGG. I do not have permission to distribute the latest version of KEGG's files, so you would need to download them yourself using the KEGG API, and ensure you were following their license terms (e.g., I believe you need to pay for commercial use).


Cheers,

Gavin

**Comment by EJS01** [comment]
Hi Gavin, 

Thank you for getting back to me. I have another question:

Following the R scripts and BRITE map you've provided, is it okay for me to still use the results even if the value at the end is "FALSE"?

identical(test_ko_L3_sorted, orig_ko_L3)
[1] FALSE

[run 2 using Rcode_categorize like Picrust1 - Copy.docx](https://github.com/user-attachments/files/17219930/run.2.using.Rcode_categorize.like.Picrust1.-.Copy.docx)

**Comment by gavinmdouglas** [comment]
Looking back at the code -- `orig_ko_L3` is the expected output, and `test_ko_L3_sorted` is the observed output, so it does seem like an issue if they don't match. How do the two tables differ?

**Comment by EJS01** [comment]
Hi, here are the outputs after each command

test_ko_L3 <- categorize_by_function_l3(test_ko, kegg_brite_map)
288 obs. of 12 variables

orig_ko_L3 <- read.table("test_ko_L3.tsv", header=TRUE, sep="\t", row.names=1, skip=1, comment.char="", quote="")
287 obs. of  12 variables

orig_ko_L3 <- orig_ko_L3[, -which(colnames(orig_ko_L3) == "KEGG_Pathways")]
287 obs. of 0 variables

orig_ko_L3 <- orig_ko_L3[-which(rowSums(orig_ko_L3) == 0),]
287 obs. of 0 variables

test_ko_L3_sorted <- test_ko_L3[rownames(orig_ko_L3), ]
0 obs. of 12 variables

**Comment by gavinmdouglas** [comment]
It looks like you are losing all columns after running this R command:
```
orig_ko_L3 <- orig_ko_L3[, -which(colnames(orig_ko_L3) == "KEGG_Pathways")]
```

Also, just to be clear - did you run PICRUSt1 on your file as well to compare that you are getting the pathways regrouped in the same way? That commented R code was just showing a check I ran when I originally wrote it to ensure that the regrouping was happening in the same way. That check is not necessary for every user actually, which was your original question -- sorry for the confusion.

Also please note that that was just a quick example of how to regroup a table in R, and is not maintained code.

**Comment by EJS01** [comment]
Hi Gavin,

I used the KO values from PICRUSt2. 
[pred_metagenome_unstrat.txt](https://github.com/user-attachments/files/17272625/pred_metagenome_unstrat.txt)

If that is the case, can you please check if my product is already correct?
[test_ko_l2.txt](https://github.com/user-attachments/files/17272651/test_ko_l2.txt)

**Comment by gavinmdouglas** [comment]
Hi @EJS01,

The purpose of that R command is to regroup a table of KOs into KEGG pathways using the same approach as PICRUSt1. A different approach is used in PICRUSt2, so the values will not match. I think the approach in PICRUSt2 makes more sense, which is why regrouping approach was dropped in PICRUSt2. However, sometimes users want to nonetheless use the PICRUSt1 regrouping approach, which is why I gave the example of this R command.


Hope that helps,

Gavin
