### ISSUE TITLE
Picrust 2 KEGG Pathway to predict KO Pathway abundance.

### ISSUE THREAD

**Issue by upasanagupta127** [gavinmdouglas/picrust2_manuscript#4]
Hello everyone,

I have carried out PICRUST 2 analysis using standalone version and have carried out full pathway pipeline where I got KO_metagenome_out/pred_metagenome_unstrat.tsv.gz and upon proceeding with KEGG pathway analysis ( Referred FAQ section of Picrust 2) the code written their takes the Strat.tsv as an input file. but I got unstrap.tsv,gz file. kindly suggest , how to get KO pathway abundance table.

Thanks and regards
Upasana Gupta

**Comment by gavinmdouglas** [comment]
Hey there,

You can input the unstratified KO table input and you will get unstratified KEGG pathways. Does that answer your question?


Thanks,

Gavin

**Comment by upasanagupta127** [comment]
Yes, 

You are right. But on putting the unstrat. Tsv file as an input. I am getting errors

**Comment by upasanagupta127** [comment]
Could you kindly suggest me the code that will not give any error on running over the terminal.

**Comment by gavinmdouglas** [comment]
Can you confirm that you are using the latest version (v2.4.1)? Also, what exact commands and errors are you getting?


Thanks,

Gavin

**Comment by upasanagupta127** [comment]
pathway_pipeline.py -i KO_metagenome_out/pred_metagenome_unstrat.tsv.gz -o KEGG_pathways_out --no_regroup --map picrust2/picrust2/default_files/pathway_mapfiles/KEGG_pathways_to_KO.tsv

Traceback (most recent call last):
  File "/Users/hp/miniconda3/envs/picrust2/bin/pathway_pipeline.py", line 211, in <module>
    main()
  File "/Users/hp/miniconda3/envs/picrust2/bin/pathway_pipeline.py", line 144, in main
    check_files_exist([args.input, args.map])
  File "/Users/hp/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/util.py", line 380, in check_files_exist
    ", ".join(missing_files))
ValueError: These input files were not found: KO_metagenome_out/pred_metagenome_unstrat.tsv.gz, picrust2/picrust2/default_files/pathway_mapfiles/KEGG_pathways_to_KO.tsv

this error I am getting when running on the terminal.
and yes I have installed Picrust2 v2.1.4

**Comment by gavinmdouglas** [comment]
Hey @upasanagupta127,

The error is that the input file cant be found - so `KO_metagenome_out/pred_metagenome_unstrat.tsv.gz` isn't present. If you point to the correct file location it should work.


Cheers,

Gavin

**Comment by fquerdasi** [comment]
Hi @gavinmdouglas,

I obtained a very similar error, except the only missing input file was the picrust2/picrust2/default_files/pathway_mapfiles/KEGG_pathways_to_KO.tsv. I have installed and am running picrust2 version 2.4.2, which is later than the version you specified above.

Could you please confirm that file is still included with picrust2 version 2.4.2?

Thank you!
Fran

**Comment by gavinmdouglas** [comment]
Closing the original issue as I think it was resolved

**Comment by gavinmdouglas** [comment]
Hey @fquerdasi,

Yes you can see it in this section of the repository: https://github.com/picrust/picrust2/tree/master/picrust2/default_files/pathway_mapfiles

If you're having trouble finding it you might want to re-download the source package from GitHub. 


Hopefully that helps!

Gavin
