### ISSUE TITLE
Having trouble pairing 16S and metagenome data for each of the 22 soil samples

### ISSUE THREAD

**Issue by jialiu232** [gavinmdouglas/picrust2_manuscript#5]
Hi there, 

I noticed that you have nicely included a file introducing how to pair 16S and metagenome for each HMP sample. I am having trouble pairing the 16S and metagenome for the 22 blueberry soil samples. From the NCBI sequence read archive, I found from Bioproject (PRJNA389786) 145 numbers of 16S samples for these soil, and from BIoproject (PRJNA484230) 92 numbers of Metagenome samples for these soil. But I am not sure how to pair between 16S and Metagenome, and what experimental treatments each sample is under. It would be great if you could explain how you did this in the paper. Many thanks.

Best,
Jia

**Comment by gavinmdouglas** [comment]
Hey @jialiu232,

I actually got the files and metadata file directly from the lead author of that study (of which I am a co-author too). I'll ask her about this as that's clearly an issue if the metadata wasn't made available!

Would you mind emailing me at <img width="144" alt="gmail_screenshot" src="https://user-images.githubusercontent.com/12489683/137164345-ab66bcbb-76aa-4e4d-a5fe-f0d38a7961da.png"> so I can forward your concern to her and cc' you?


Cheers,

Gavin

**Comment by jialiu232** [comment]
> Hey @jialiu232,
> 
> I actually got the files and metadata file directly from the lead author of that study (of which I am a co-author too). I'll ask her about this as that's clearly an issue if the metadata wasn't made available!
> 
> Would you mind emailing me at <img alt="gmail_screenshot" width="144" src="https://user-images.githubusercontent.com/12489683/137164345-ab66bcbb-76aa-4e4d-a5fe-f0d38a7961da.png"> so I can forward your concern to her and cc' you?
> 
> Cheers,
> 
> Gavin

Thank you very much for your prompt response! I just emailed you about the problem, thanks!

Best,
Jia
