### ISSUE TITLE
in version 2.4.2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

### ISSUE THREAD

**Issue by marwa38** [gavinmdouglas/picrust2_manuscript#6]
hello 

I ran this pipeline before using 2.3.0 and I haven't seen this warning before like when I saw it in version 2.4.2
Do I have to worry and fix something?
```

/home/r01mt19/picrust2-2.4.2/picrust2/pathway_pipeline.py:1243: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df = new_df.append(new_subset)
```

thanks

**Comment by gavinmdouglas** [comment]
That's just a warning that in future versions of pandas there will be an incompatibility so you can ignore that.


Cheers,

Gavin

**Comment by marwa38** [comment]
many thanks, @gavinmdouglas 
if you don't mind I have another query related to the new version?
for `description_mapfiles`
```
# [1] "cog_info.tsv.gz"              "ec_level4_info.tsv.gz"        "KEGG_modules_info.tsv.gz"     "KEGG_pathways_info.tsv.gz"   
# [5] "ko_info.tsv.gz"               "metacyc_pathways_info.txt.gz" "pfam_info.tsv.gz"             "tigrfam_info.tsv.gz" 
```
where can I find them
I tried in conda 
`locate description_mapfiles ` and couldn't find them (although I found them in version 2.3.0), I guess they have a different folder name?

Cheers

**Comment by gavinmdouglas** [comment]
I'm not familiar with the `locate` command, but those files are found in this section of the repo: https://github.com/picrust/picrust2/tree/master/picrust2/default_files/description_mapfiles

They are certainly meant to be downloaded when the tool is installed with conda, but if you're running into issues you can install from source instead.


Cheers,

Gavin
