### ISSUE TITLE
plotting functional prediction analysis?

### ISSUE THREAD

**Issue by marwa38** [gavinmdouglas/picrust2_manuscript#7]
Hello @gavinmdouglas 

I have run picrust2 & ALDEx2 for statistical analysis (I reproduced this tutorial: https://ycl6.github.io/16S-Demo/4_picrust2_tutorial.html). 
Could you please suggest a way for plotting as follows?
![image](https://user-images.githubusercontent.com/68851733/151786111-bb57b70c-72b5-450b-9168-81e78fff6fa0.png)
![image](https://user-images.githubusercontent.com/68851733/151786145-ed93761f-39b9-48a3-9b2c-1fad284eb17e.png)
![image](https://user-images.githubusercontent.com/68851733/151786883-1308ca85-a7f5-4a64-954b-ae519e3668e2.png)

Your suggestions and help are much appreciated. 
Cheers

**Comment by gavinmdouglas** [comment]
Hi @marwa38,

That last plot looks like it was created by STAMP. I believe the first two plots were created in R. I don't have a tutorial for how to make such plots to point you to unfortunately.


Gavin

**Comment by marwa38** [comment]
many thanks for your reply :)
